<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\File.Validator.Application\File.Validator.Application.csproj" />
    <ProjectReference Include="..\File.Validator.Infrastructure\File.Validator.Infrastructure.csproj" />
    <ProjectReference Include="..\File.Validator.Presentation\File.Validator.Presentation.csproj" />
  </ItemGroup>

</Project>
